import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

// Disable caching for the entire website
export const dynamic = 'force-dynamic';
export const revalidate = 0;

const inter = Inter({subsets: ["latin"]});
import {cn} from "@/lib/utils";
import Header from "./components/Header";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark">
        <body className={cn(inter.className, "dark:bg-black dark:text-white")}>
        <Header/>
        {children}
        <Footer/>
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: '#1e1e1e',
              color: '#fff',
            },
          }}
        />
        </body>
        </html>
    );
}